Test Program Syntactic check

Board: 69N0GUM10C01P-01 11-12-2009 23:27:51


Skip step check ...
STAMP port check ...
STAMP port check OK

Vectorless test step parameter check ...
Vectorless test step parameter check OK

Version 0 test program check ...
Version 0 test program check OK

Warning : No OnPower Test Program

No Function Test Program

There are 0 errors.
There are 0 license errors.
There are 0 warnings.


